In [10]:
import pandas as pd
import json
from pandas.io.json import json_normalize
from pandas.io.json import read_json

pd.set_option('display.max_rows', 200)
%matplotlib inline

#twit29Tusk = '/home/jay/Downloads/sdsv/CASA0006dsss/BrexitMoon/tw/20190329Tusk.json'
twit29Tusk = '/home/jay/Downloads/sdsv/CASA0006dsss/BrexitMoon/tw-test/20190329TuskTruncated.json'
json29Tusk = []

with open(twit29Tusk) as tweetInput:
    for line in tweetInput:
        json29Tusk.append(json.loads(line))
    
dict29Tusk = json29Tusk[0]
print('twit29Tusk is type', type (twit29Tusk))    # it is a string 
print('json29Tusk is type', type (json29Tusk))    # it is a list
print('dict29Tusk is type', type (dict29Tusk))    # it is a dictionary

# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.json.json_normalize.html#pandas.io.json.json_normalize

# json_normalize(dict29Tusk)

json_normalize(dict29Tusk)

twit29Tusk is type <class 'str'>
json29Tusk is type <class 'list'>
dict29Tusk is type <class 'list'>

,contributors,coordinates,created_at,display_text_range,entities.hashtags,entities.media,entities.symbols,entities.urls,entities.user_mentions,extended_entities.media,...,user.profile_text_color,user.profile_use_background_image,user.protected,user.screen_name,user.statuses_count,user.time_zone,user.translator_type,user.url,user.utc_offset,user.verified
0,None,None,Fri Mar 29 20:49:39 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,steveforman72,35456,None,none,None,None,False
1,None,None,Fri Mar 29 20:45:22 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,tallison54,331754,None,none,None,None,False
2,None,None,Fri Mar 29 20:39:18 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [109, 114]}]",NaN,[],[],"[{'screen_name': 'kolter_hugh', 'name': 'Kolte...",NaN,...,333333,True,False,zlywest,14381,None,none,None,None,False
3,None,None,Fri Mar 29 20:36:19 +0000 2019,NaN,"[{'text': 'Brexit', 'indices': [0, 7]}, {'text...",NaN,[],"[{'url': 'https://t.co/hva3cZifKb', 'expanded_...",[],NaN,...,333333,True,False,luigiluccarini,1857,None,none,https://scenarieconomici.it/,None,False
4,None,None,Fri Mar 29 20:29:58 +0000 2019,NaN,"[{'text': 'PiS', 'indices': [26, 30]}, {'text'...",NaN,[],[],"[{'screen_name': 'pisorgpl', 'name': 'Prawo i ...",NaN,...,333333,True,False,16maciek16,9969,None,none,None,None,False
5,None,None,Fri Mar 29 20:15:54 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,England72208605,536,None,none,None,None,False
6,None,None,Fri Mar 29 20:15:29 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [109, 114]}]",NaN,[],[],"[{'screen_name': 'kolter_hugh', 'name': 'Kolte...",NaN,...,333333,True,False,76Jozefow,962,None,none,None,None,False
7,None,None,Fri Mar 29 20:14:58 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [109, 114]}]",NaN,[],[],"[{'screen_name': 'kolter_hugh', 'name': 'Kolte...",NaN,...,333333,True,False,BoKrause3,14803,None,none,None,None,False
8,None,None,Fri Mar 29 20:03:59 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [109, 114]}]",NaN,[],[],"[{'screen_name': 'kolter_hugh', 'name': 'Kolte...",NaN,...,000000,False,False,polskawruinie2,18497,None,none,None,None,False
9,None,None,Fri Mar 29 20:02:57 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [109, 114]}]",NaN,[],[],"[{'screen_name': 'kolter_hugh', 'name': 'Kolte...",NaN,...,333333,True,False,XenuThetan,4946,None,none,None,None,False
10,None,None,Fri Mar 29 19:56:31 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [109, 114]}]",NaN,[],[],"[{'screen_name': 'kolter_hugh', 'name': 'Kolte...",NaN,...,000000,False,False,MWardzyniakowa,131968,None,none,None,None,False
11,None,None,Fri Mar 29 19:54:01 +0000 2019,NaN,"[{'text': 'Stopbrexit', 'indices': [122, 133]}...",NaN,[],[],"[{'screen_name': 'Gordon1000', 'name': 'Gordon...",NaN,...,333333,False,False,compellingsites,280836,None,none,http://www.compelling.org.uk,None,False
12,None,None,Fri Mar 29 19:53:40 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [109, 114]}]",NaN,[],[],"[{'screen_name': 'kolter_hugh', 'name': 'Kolte...",NaN,...,333333,True,False,Archie_Choar,155186,None,none,None,None,False
13,None,None,Fri Mar 29 19:53:28 +0000 2019,NaN,"[{'text': 'Stopbrexit', 'indices': [106, 117]}]",NaN,[],"[{'url': 'https://t.co/lKUHy2IvFy', 'expanded_...",[],NaN,...,333333,True,False,Gordon1000,199408,None,none,None,None,False
14,None,None,Fri Mar 29 19:53:04 +0000 2019,"[0, 140]","[{'text': 'Tusk', 'indices': [92, 97]}]",NaN,[],"[{'url': 'https://t.co/oFOeb9xTQm', 'expanded_...",[],NaN,...,333333,True,False,kolter_hugh,1805,None,none,None,None,False
15,None,None,Fri Mar 29 19:48:06 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,000000,False,False,redial999,45489,None,none,None,None,False
16,None,None,Fri Mar 29 19:29:28 +0000 2019,NaN,"[{'text': 'StevieNicks', 'indices': [45, 57]},...",NaN,[],[],"[{'screen_name': 'StevieNicksEdge', 'name': '💖...",NaN,...,000000,False,False,retrositcom,7353,None,none,None,None,False
17,None,None,Fri Mar 29 19:28:48 +0000 2019,"[0, 140]","[{'text': 'StevieNicks', 'indices': [10, 22]},...",NaN,[],"[{'url': 'https://t.co/7UkintA9nQ', 'expanded_...",[],NaN,...,333333,True,False,StevieNicksEdge,11854,None,none,None,None,False
18,None,None,Fri Mar 29 19:27:43 +0000 2019,"[0, 140]","[{'text': 'StevieNicks', 'indices': [13, 25]},...",NaN,[],"[{'url': 'https://t.co/iI7uTwM1Z2', 'expanded_...",[],NaN,...,333333,True,False,StevieNicksEdge,11854,None,none,None,None,False
19,None,None,Fri Mar 29 19:19:36 +0000 2019,NaN,[],NaN,[],"[{'url': 'https://t.co/ACoLwvVU8m', 'expanded_...",[],NaN,...,666666,True,False,StarcadeTV1,53,None,none,http://www.youtube.com/user/StarcadeTV,None,False
20,None,None,Fri Mar 29 19:18:20 +0000 2019,"[0, 140]","[{'text': 'Podcast', 'indices': [24, 32]}, {'t...",NaN,[],"[{'url': 'https://t.co/bZQiNJq43R', 'expanded_...","[{'screen_name': 'barometroradio', 'name': 'ba...",NaN,...,333333,True,False,adrianvguzman,119460,None,none,http://www.loscaballerosdeldinero.com,None,False
21,None,None,Fri Mar 29 19:15:08 +0000 2019,"[0, 140]","[{'text': 'StevieNicks', 'indices': [9, 21]}, ...",NaN,[],"[{'url': 'https://t.co/Xhfm1vQiqi', 'expanded_...",[],NaN,...,333333,True,False,StevieNicksEdge,11854,None,none,None,None,False
22,None,None,Fri Mar 29 19:14:22 +0000 2019,NaN,"[{'text': 'StevieNicks', 'indices': [45, 57]},...",NaN,[],[],"[{'screen_name': 'StevieNicksEdge', 'name': '💖...",NaN,...,666666,True,False,VampWriterGRRL,207068,None,none,http://robindianastudios.etsy.com,None,False
23,None,None,Fri Mar 29 19:14:08 +0000 2019,NaN,"[{'text': 'StevieNicks', 'indices': [45, 57]},...",NaN,[],[],"[{'screen_name': 'StevieNicksEdge', 'name': '💖...",NaN,...,333333,True,False,anabrown75,64842,None,none,http://www.reverbnation.com/anabrown,None,False
24,None,None,Fri Mar 29 19:11:21 +0000 2019,"[0, 140]","[{'text': 'StevieNicks', 'indices': [37, 49]},...",NaN,[],"[{'url': 'https://t.co/DYBzrlX25c', 'expanded_...",[],NaN,...,333333,True,False,StevieNicksEdge,11854,None,none,None,None,False
25,None,None,Fri Mar 29 19:10:52 +0000 2019,NaN,"[{'text': 'May', 'indices': [57, 61]}, {'text'...",NaN,[],[],"[{'screen_name': 'fabrizio_sn', 'name': 'Fabri...",NaN,...,000000,False,False,FabioCosta_USA,9060,None,none,None,None,False
26,None,None,Fri Mar 29 19:10:30 +0000 2019,"[0, 140]","[{'text': 'StevieNicks', 'indices': [24, 36]},...",NaN,[],"[{'url': 'https://t.co/KzGVupZKtl', 'expanded_...",[],NaN,...,333333,True,False,StevieNicksEdge,11854,None,none,None,None,False
27,None,None,Fri Mar 29 19:05:28 +0000 2019,"[0, 140]","[{'text': 'May', 'indices': [40, 44]}, {'text'...",NaN,[],"[{'url': 'https://t.co/0pDpdCrAtl', 'expanded_...",[],NaN,...,333333,True,False,fabrizio_sn,22313,None,none,None,None,False
28,None,None,Fri Mar 29 18:57:42 +0000 2019,"[14, 140]","[{'text': 'backstop', 'indices': [76, 85]}]",NaN,[],"[{'url': 'https://t.co/0zuaLw2MGn', 'expanded_...","[{'screen_name': 'SkyNewsBreak', 'name': 'Sky ...",NaN,...,333333,True,False,alwilkinson_,416,None,none,None,None,False
29,None,None,Fri Mar 29 18:43:05 +0000 2019,NaN,[],NaN,[],[],"[{'screen_name': 'True_Poland', 'name': 'True ...",NaN,...,333333,True,False,LilaNajda,9206,None,none,None,None,False
30,None,None,Fri Mar 29 18:39:48 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,Alice666Uk,2621,None,none,None,None,False
31,None,None,Fri Mar 29 18:34:01 +0000 2019,"[0, 81]","[{'text': 'AferaAutobusowa', 'indices': [0, 16...","[{'id': 1111697745876828161, 'id_str': '111169...",[],[],[],"[{'id': 1111697745876828161, 'id_str': '111169...",...,000000,False,False,Adam_978,5501,None,none,None,None,False
32,None,None,Fri Mar 29 18:22:49 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,PlusUnperson,569,None,none,None,None,False
33,None,None,Fri Mar 29 18:20:24 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,walshr108,150875,None,none,None,None,False
34,None,None,Fri Mar 29 18:09:37 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,bobzanchi,2867,None,none,None,None,False
35,None,None,Fri Mar 29 17:56:46 +0000 2019,NaN,"[{'text': 'Brexit', 'indices': [127, 134]}, {'...",NaN,[],[],[],NaN,...,333333,True,False,MaleckiJerzy,619,None,none,None,None,False
36,None,None,Fri Mar 29 17:48:20 +0000 2019,NaN,"[{'text': 'EU', 'indices': [14, 17]}, {'text':...",NaN,[],"[{'url': 'https://t.co/vJz0ydyOFK', 'expanded_...","[{'screen_name': 'ZDFheute', 'name': 'ZDF heut...",NaN,...,000000,False,False,Genius_Play_U,66018,None,none,None,None,False
37,None,None,Fri Mar 29 17:47:03 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [21, 26]}, {'text...",NaN,[],[],"[{'screen_name': 'BirnstinglausRo', 'name': 'T...",NaN,...,333333,True,False,HansMll54898918,6894,None,none,None,None,False
38,None,None,Fri Mar 29 17:45:49 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,Lorrain01056003,860,None,none,None,None,False
39,None,None,Fri Mar 29 17:45:42 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [21, 26]}, {'text...",NaN,[],[],"[{'screen_name': 'BirnstinglausRo', 'name': 'T...",NaN,...,333333,True,False,FDP4ever5,7056,None,none,None,None,False
40,None,None,Fri Mar 29 17:44:23 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [21, 26]}, {'text...",NaN,[],[],"[{'screen_name': 'BirnstinglausRo', 'name': 'T...",NaN,...,333333,True,False,ZuvieleRechte,7144,None,none,None,None,False
41,None,None,Fri Mar 29 17:43:08 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [21, 26]}, {'text...",NaN,[],[],"[{'screen_name': 'BirnstinglausRo', 'name': 'T...",NaN,...,333333,True,False,FritzLiberal,7030,None,none,None,None,False
42,None,None,Fri Mar 29 17:42:03 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [21, 26]}, {'text...",NaN,[],[],"[{'screen_name': 'BirnstinglausRo', 'name': 'T...",NaN,...,000000,False,False,BirnstinglausRo,16650,None,none,None,None,False
43,None,None,Fri Mar 29 17:36:54 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,666666,True,False,deves46,3447,None,none,None,None,False
44,None,None,Fri Mar 29 17:32:01 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [0, 5]}, {'text':...",NaN,[],"[{'url': 'https://t.co/92uOE4365Y', 'expanded_...",[],NaN,...,000000,False,False,BirnstinglausRo,16650,None,none,None,None,False
45,None,None,Fri Mar 29 17:17:34 +0000 2019,NaN,"[{'text': 'TheresaMay', 'indices': [0, 11]}, {...",NaN,[],"[{'url': 'https://t.co/aV2O4QxcdV', 'expanded_...",[],NaN,...,333333,True,False,ann_mcgoldrick,9530,None,none,None,None,False
46,None,None,Fri Mar 29 17:03:19 +0000 2019,"[0, 140]","[{'text': 'Brexit', 'indices': [5, 12]}, {'tex...",NaN,[],"[{'url': 'https://t.co/dUY9Jce72J', 'expanded_...",[],NaN,...,333333,False,False,LeenBoer,18203,None,none,None,None,False
47,None,None,Fri Mar 29 16:43:29 +0000 2019,NaN,"[{'text': 'StevieNicks', 'indices': [28, 40]},...",NaN,[],[],"[{'screen_name': 'StevieNicksEdge', 'name': '💖...",NaN,...,666666,True,False,VampWriterGRRL,207068,None,none,http://robindianastudios.etsy.com,None,False
48,None,None,Fri Mar 29 16:42:42 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,TBayfield,6849,None,none,None,None,False
49,None,None,Fri Mar 29 16:42:41 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,PeaWea4,9534,None,none,None,None,False
50,None,None,Fri Mar 29 16:40:25 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,LegrandeeHoward,65630,None,none,None,None,False
51,None,None,Fri Mar 29 16:35:27 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,58031A,True,False,Pirate6665,58057,None,none,None,None,False
52,None,None,Fri Mar 29 16:35:18 +0000 2019,NaN,"[{'text': 'StevieNicks', 'indices': [42, 54]},...",NaN,[],[],"[{'screen_name': 'StevieNicksEdge', 'name': '💖...",NaN,...,333333,True,False,happygirl417,38296,None,none,None,None,False
53,None,None,Fri Mar 29 16:34:43 +0000 2019,NaN,"[{'text': 'StevieNicks', 'indices': [28, 40]},...",NaN,[],[],"[{'screen_name': 'StevieNicksEdge', 'name': '💖...",NaN,...,333333,True,False,happygirl417,38296,None,none,None,None,False
54,None,None,Fri Mar 29 16:34:13 +0000 2019,"[29, 140]",[],NaN,[],"[{'url': 'https://t.co/cQKdHUjm8g', 'expanded_...","[{'screen_name': 'RundfunkEuropa', 'name': 'Łu...",NaN,...,666666,True,False,artistyadamu,580,None,none,None,None,False
55,None,None,Fri Mar 29 16:33:42 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,Allampone1,3949,None,none,None,None,False
56,None,None,Fri Mar 29 16:33:33 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,663B12,True,False,tcjc,4086,None,none,None,None,False
57,None,None,Fri Mar 29 16:31:32 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,Ianjack69898251,179,None,none,None,None,False
58,None,None,Fri Mar 29 16:27:09 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,EddieFinanLufc,179,None,none,None,None,False
59,None,None,Fri Mar 29 16:26:04 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,000000,False,False,ChrisJHudson,69085,None,none,http://gab.ai/chrisjhudson,None,False
60,None,None,Fri Mar 29 16:22:04 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [7, 12]}, {'text'...",NaN,[],"[{'url': 'https://t.co/0ubcr8zYgC', 'expanded_...","[{'screen_name': 'Parlimag', 'name': 'Parliame...",NaN,...,616163,True,False,GeoCapitalEcon,23079,None,regular,https://paper.li/SpecBanking/1371220463#/,None,False
61,None,None,Fri Mar 29 16:15:43 +0000 2019,NaN,"[{'text': 'GiletsJaunes', 'indices': [59, 72]}...","[{'id': 1111649306539425792, 'id_str': '111164...",[],[],"[{'screen_name': 'norfolkpainter', 'name': 'He...","[{'id': 1111649306539425792, 'id_str': '111164...",...,333333,True,False,5B8BI,28828,None,none,None,None,False
62,None,None,Fri Mar 29 16:14:25 +0000 2019,NaN,"[{'text': 'Stopbrexit', 'indices': [81, 92]}, ...",NaN,[],"[{'url': 'https://t.co/tgaHtD20Et', 'expanded_...",[],NaN,...,333333,True,False,Gordon1000,199408,None,none,None,None,False
63,None,None,Fri Mar 29 16:08:38 +0000 2019,NaN,"[{'text': 'Brexit', 'indices': [35, 42]}, {'te...",NaN,[],[],"[{'screen_name': 'markuspreiss', 'name': 'Mark...",NaN,...,505050,True,False,DarkerMatrix,73562,None,none,None,None,False
64,None,None,Fri Mar 29 15:51:30 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [0, 5]}, {'text':...",NaN,[],"[{'url': 'https://t.co/n5tHqsmdww', 'expanded_...",[],NaN,...,333333,True,False,EuroZpravycz,67903,None,none,http://www.eurozpravy.cz,None,False
65,None,None,Fri Mar 29 15:49:56 +0000 2019,NaN,"[{'text': 'Brexit', 'indices': [35, 42]}, {'te...",NaN,[],[],"[{'screen_name': 'markuspreiss', 'name': 'Mark...",NaN,...,000000,False,False,MatthiasFranck,60349,None,none,None,None,False
66,None,None,Fri Mar 29 15:46:36 +0000 2019,"[0, 140]","[{'text': 'Stopbrexit', 'indices': [86, 97]}, ...",NaN,[],"[{'url': 'https://t.co/I5ptavPOVb', 'expanded_...",[],NaN,...,333333,True,False,Gordon1000,199408,None,none,None,None,False
67,None,None,Fri Mar 29 15:40:45 +0000 2019,NaN,"[{'text': 'UltimOra', 'indices': [13, 22]}, {'...",NaN,[],"[{'url': 'https://t.co/0kxapzvQk0', 'expanded_...","[{'screen_name': 'SkyTG24', 'name': 'Sky tg24'...",NaN,...,333333,True,False,paolo77jpm,15090,None,none,None,None,False
68,None,None,Fri Mar 29 15:38:46 +0000 2019,NaN,"[{'text': 'Tusk', 'indices': [0, 5]}, {'text':...",NaN,[],"[{'url': 'https://t.co/64laM1CdEm', 'expanded_...",[],NaN,...,333333,True,False,clubbers007,10689,None,none,None,None,False
69,None,None,Fri Mar 29 15:37:13 +0000 2019,NaN,"[{'text': 'EU', 'indices': [19, 22]}, {'text':...","[{'id': 1111652579795185666, 'id_str': '111165...",[],"[{'url': 'https://t.co/v03GSz9XsX', 'expanded_...","[{'screen_name': 'anadoluagency', 'name': 'ANA...","[{'id': 1111652579795185666, 'id_str': '111165...",...,000000,False,False,nurrabus,2514,None,none,None,None,False
70,None,None,Fri Mar 29 15:35:38 +0000 2019,NaN,"[{'text': 'EU', 'indices': [19, 22]}, {'text':...","[{'id': 1111652579795185666, 'id_str': '111165...",[],"[{'url': 'https://t.co/v03GSz9XsX', 'expanded_...","[{'screen_name': 'anadoluagency', 'name': 'ANA...","[{'id': 1111652579795185666, 'id_str': '111165...",...,333333,True,False,jamaan78,81455,None,none,None,None,False
71,None,None,Fri Mar 29 15:34:56 +0000 2019,NaN,"[{'text': 'EU', 'indices': [19, 22]}, {'text':...","[{'id': 1111652579795185666, 'id_str': '111165...",[],"[{'url': 'https://t.co/v03GSz9XsX', 'expanded_...","[{'screen_name': 'anadoluagency', 'name': 'ANA...","[{'id': 1111652579795185666, 'id_str': '111165...",...,3E4415,True,False,meteuu,129470,None,regular,None,None,False